# Dockerfile.hw3

# Use a base image with Python
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Install dependencies
RUN pip install pandas numpy scikit-learn mlflow pyarrow requests

# Copy the script and the shell script into the container
COPY hw3.py .
COPY start_hw3.sh .

# Make the shell script executable
RUN chmod +x start_hw3.sh

# Run the shell script
CMD ["./start_hw3.sh"]